{
 "title": "IDS2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Geolocation",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "attack_count{instance=\"localhost:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_status{job=\"server_status\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tcp_ports{job=\"monitor_ports\"}",
     "legendFormat": "TCP"
    },
    {
     "expr": "udp_ports{job=\"monitor_ports\"}",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Server UpTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_uptime_seconds{job=\"server_uptime_seconds\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 4 },
   "targets": [
    {
     "expr": "network_bytes_sent{job=\"network_metrics\"}",
     "legendFormat": "Upload"
    },
    {
     "expr": "network_bytes_recv{job=\"network_metrics\"}",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "HTTP-Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"http_requests_total\"}",
     "legendFormat": "HTTP-Requests_Total"
    },
    {
     "expr": "http_requests_total{job=\"http_response_duration_seconds\"}",
     "legendFormat": "HTTP-Response_Duration"
    }
   ]
  },
  {
   "title": "Prediction And Intrusion",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "intrusion_tcp_total{job=\"intrusion_tcp_total\"}",
     "legendFormat": "TCP-IP"
    },
    {
     "expr": "intrusion_icmp_total{job=\"intrusion_icmp_total\"}",
     "legendFormat": "ICMP"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "network_intrusion_attempts_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}