{
 "title": "TESTE-02-IDS Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP-Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"http_requests_total\"}",
     "legendFormat": "HTTP-Requests_Total"
    },
    {
     "expr": "http_requests_total{job=\"http_response_duration_seconds\"}",
     "legendFormat": "HTTP-Response_Duration"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_status{job=\"server_status\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server UpTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_uptime_seconds{job=\"server_uptime_seconds\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction And Intrusion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "intrusion_tcp_total{job=\"intrusion_tcp_total\"}",
     "legendFormat": "TCP-IP"
    },
    {
     "expr": "intrusion_icmp_total{job=\"intrusion_icmp_total\"}",
     "legendFormat": "ICMP"
    }
   ]
  }
 ]
}